language: python
python:
  - "3.5"
install:
  - pip install -e .
  - pip install coveralls
  - pip install flake8==2.6.2
script:
  - python setup.py test
  - python setup.py flake8
after_success:
  - coveralls
