swagger: "2.0"

info:
  title: Lizzy
  version: "1.0"

produces:
  - application/json


securityDefinitions:
  oauth:
    type: oauth2
    flow: password
    tokenUrl: "{{token_url}}"
    x-tokenInfoUrl: "{{token_info_url}}"
    scopes:
        "{{deployer_scope}}": Can deploy and change stacks

paths:
  /stacks:
    get:
      summary: List all stacks
      operationId: lizzy.api.all_stacks
      security:
        - oauth:
            - "{{deployer_scope}}"
      responses:
        200:
          description: List of stacks
          schema:
            type: array
            items:
              $ref: '#/definitions/stack'
    post:
      summary: Create new stack
      operationId: lizzy.api.new_stack
      responses:
        200:
          description: Stack to be created
          schema:
            type: string
            $ref: '#/definitions/stack'
      security:
        - oauth:
            - "{{deployer_scope}}"
      parameters:
        - name: new_stack
          required: true
          in: body
          schema:
            type: object
            $ref: '#/definitions/new_stack'
  /stacks/{stack-id}:
    get:
      summary: Get a stack
      description: Gets a stack.by id.
      operationId: lizzy.api.get_stack
      security:
        - oauth:
            - "{{deployer_scope}}"
      responses:
        200:
          description: Stack information
          schema:
            type: string
            $ref: '#/definitions/stack'
      parameters:
        - name: stack-id
          in: path
          description: Stack Id
          required: true
          type: string
    delete:
      summary: Delete a stack
      description: Deletes the stack.
      operationId: lizzy.api.delete_stack
      responses:
        200:
          description: Stack to be deleted
          schema:
            type: string
            $ref: '#/definitions/stack'
      security:
        - oauth:
            - "{{deployer_scope}}"
      parameters:
        - name: stack-id
          in: path
          description: Deployment id
          required: true
          type: string
    patch:
      summary: Update stack
      operationId: lizzy.api.patch_stack
      responses:
        200:
          description: Stack with changes
          schema:
            type: object
            $ref: '#/definitions/stack'
      security:
        - oauth:
            - "{{deployer_scope}}"
      parameters:
      - name: stack-id
        in: path
        description: Deployment id
        required: true
        type: string
      - name: stack_patch
        in: body
        required: true
        schema:
          type: object
          $ref: '#/definitions/stack_patch'
definitions:
  new_stack:
    properties:
      image_version:
        type: string
        description: Docker image version to deploy
      keep_stacks:
        type: integer
        description: Number of older stacks to keep
      new_traffic:
        type: integer
        description: Percentage of the traffic to be routed to new version
      senza_yaml:
        type: string
        description: YAML to provide to senza
    required:
      - image_version
      - keep_stacks
      - new_traffic
      - senza_yaml
  stack:
    properties:
      stack_id:
        type: string
        description: Unique ID for the stack
      creation_time:
        type: string
        format: dateTime
        description: Date and time of stack creation on lizzy in ISO 8601 format
      image_version:
        type: string
        description: Docker image deployed
      senza_yaml:
        type: string
        description: YAML to provide to senza
      stackName:
        type: string
        description: Cloud formation stack name prefix
      stackVersion:
        type: string
        description: Cloud formation stack version
      status:
        type: string
        description: Cloud formation stack status
  stack_patch:
    properties:
      new_traffic:
        type: integer
        description: Percentage of the traffic to be routed to stack