swagger: "2.0"

info:
  title: Lizzy
  version: "1.0"

produces:
  - application/json


securityDefinitions:
    greendale:
        type: oauth2
        flow: password
        tokenUrl: {{token_url}}
        x-tokenInfoUrl: {{token_info_url}}
        scopes:
            {{deployer_scope}}: Can deploy and change stacks

paths:
  /stacks:
    get:
      summary: List all stacks
      operationId: lizzy.api.all_stacks
      security:
        greendale:
            - {{deployer_scope}}
    post:
      summary: Create new stack
      operationId: lizzy.api.new_stack
      responses:
        200:
          schema:
            type: string
            $ref: '#/definitions/stack'
      security:
        greendale:
            - {{deployer_scope}}
      parameters:
        - name: newStack
          required: true
          type: string
          in: body
          schema:
            $ref: '#/definitions/new_stack'
  /stacks/{stack-id}:
    get:
      summary: Get a stack
      description: Gets a stack.by id.
      operationId: lizzy.api.get_stack
      security:
        greendale:
            - uid
      responses:
        200:
          description: greeting response
          schema:
            type: string
            $ref: '#/definitions/stack'
      security:
        greendale:
            - {{deployer_scope}}
      parameters:
        - name: stack-id
          in: path
          description: Deployment id
          required: true
          type: string
    delete:
      summary: Delete a stack
      description: Deletes the stack.
      operationId: lizzy.api.delete_stack
      responses:
        200:
          description: greeting response
          schema:
            type: string
            $ref: '#/definitions/stack'
      security:
        greendale:
            - {{deployer_scope}}
      parameters:
        - name: stack-id
          in: path
          description: Deployment id
          required: true
          type: string
    patch:
      summary: Update stack
      operationId: lizzy.api.patch_stack
      responses:
        200:
          schema:
            type: string
            $ref: '#/definitions/stack'
      security:
        greendale:
            - {{deployer_scope}}
      parameters:
        - name: stack-id
          in: path
          description: Deployment id
          required: true
          type: string
        - name: stack_patch
          required: true
          type: string
          in: body
          schema:
            $ref: '#/definitions/stack_patch'
definitions:
  new_stack:
    properties:
      imageVersion:
        type: string
        description: Docker image version to deploy
      keepStacks:
        type: integer
        description: Number of older stacks to keep
      newTraffic:
        type: integer
        description: Percentage of the traffic to be routed to new version
      senzaYaml:
        type: string
        description: YAML to provide to senza
    required:
      - imageVersion
      - keepStacks
      - newTraffic
      - senzaYaml
  stack:
    properties:
      stackId:
        type: string
        description: Unique ID for the stack
      creationTime:
        type: string
        description: Date and time of stack creation on lizzy in ISO 8601 format
      imageVersion:
        type: string
        description: Docker image deployed
      senzaYaml:
        type: string
        description: YAML to provide to senza
      stackName:
        type: string
        description: Cloud formation stack name prefix
      stackVersion:
        type: string
        description: Cloud formation stack version
      status:
        type: string
        description: Cloud formation stack status
  stack_patch:
    properties:
      newTraffic:
        type: integer
        description: Percentage of the traffic to be routed to stack