swagger: "2.0"

info:
  title: Lizzy
  version: "1.0"

produces:
  - application/json


securityDefinitions:
    greendale:
        type: oauth2
        flow: password
        tokenUrl: {{token_url}}
        x-tokenInfoUrl: {{token_info_url}}
        scopes:
            uid: do everything for now

paths:
  /stacks/:
    get:
      summary: List all stacks
      operationId: lizzy.api.all_stacks
      security:
        greendale:
            - uid
    post:
      summary: Create new stack
      operationId: lizzy.api.new_stack
      responses:
        200:
          schema:
            type: string
            $ref: '#/definitions/stack'
      security:
        greendale:
            - uid
      parameters:
        - name: new_stack
          required: true
          type: string
          in: body
          schema:
            $ref: '#/definitions/new_stack'
  /stacks/{stack_id}:
    get:
      summary: Get a stack
      description: Generates a greeting message.
      operationId: lizzy.api.get_stack
      security:
        greendale:
            - uid
      responses:
        200:
          description: greeting response
          schema:
            type: string
            $ref: '#/definitions/stack'
      parameters:
        - name: stack_id
          in: path
          description: Deployment id
          required: true
          type: string

definitions:
  new_stack:
    properties:
      image_version:
        type: string
        description: Docker image version to deploy
      keep_stacks:
        type: integer
        description: Number of older stacks to keep
      new_traffic:
        type: integer
        description: Percentage of the traffic to be routed to new version
      senza_yaml:
        type: string
        description: YAML to provide to senza
    required:
      - image_version
      - keep_stacks
      - new_traffic
      - senza_yaml
  stack:
    properties:
      stack_id:
        type: string
        description: Unique ID for the stack
      image_version:
        type: string
        description: Docker image deployed
      senza_yaml:
        type: string
        description: YAML to provide to senza
      stack_name:
        type: string
        description: Cloud formation stack name prefix
      stack_version:
        type: string
        description: Cloud formation stack version
      status:
        type: string
        description: Cloud formation stack status