swagger: "2.0"

info:
  title: Lizzy
  version: "1.0"

produces:
  - application/json


securityDefinitions:
    greendale:
        type: oauth2
        flow: password
        tokenUrl: https://token.auth.zalando.com/access_token
        x-tokenInfoUrl: https://auth.zalando.com/am/oauth2/tokeninfo
        scopes:
            uid: do everything for now

paths:
  /deploy/:
    get:
      summary: List all deployments
      operationId: lizzy.api.all_deployments
      security:
        greendale:
            - uid
    post:
      summary: New deployments
      operationId: lizzy.api.new_deployment
      responses:
        200:
          schema:
            type: string
            $ref: '#/definitions/deployment'
      parameters:
        - name: new_deployment
          required: true
          type: string
          in: body
          schema:
            $ref: '#/definitions/new_deployment'
  /deploy/{deployment_id}:
    get:
      summary: Get a deployment
      description: Generates a greeting message.
      operationId: lizzy.api.deploy
      responses:
        200:
          description: greeting response
          schema:
            type: string
            $ref: '#/definitions/deployment'
      parameters:
        - name: deployment_id
          in: path
          description: Deployment id
          required: true
          type: string

definitions:
  new_deployment:
    properties:
      image_version:
        type: string
        description: Docker image version to deploy
      keep_stacks:
        type: integer
        description: Number of older stacks to keep
      new_traffic:
        type: integer
        description: Percentage of the traffic to be routed to new version
      senza_yaml:
        type: string
        description: YAML to provide to senza
    required:
      - image_version
      - keep_stacks
      - new_traffic
      - senza_yaml
  deployment:
    properties:
      deployment_id:
        type: string
        description: Unique ID for the deployment
      image_version:
        type: string
        description: Docker image version to deploy
      senza_yaml:
        type: string
        description: YAML to provide to senza
      stack_name:
        type: string
        description: Cloud formation stack name prefix
      stack_version:
        type: string
        description: Cloud formation stack version
      status:
        type: string
        description: Cloud formation stack status